/**
 * auê custom service worker — injectManifest mode
 *
 * VitePWA's `injectManifest` mode takes this file, injects the precache
 * manifest generated by Workbox (list of hashed static assets), and outputs
 * the final SW into dist/.  We then add our own push event handler on top.
 *
 * Why injectManifest instead of generateSW?
 *   generateSW creates the SW entirely from config — no room to add custom
 *   event handlers like `push`.  injectManifest keeps full control while
 *   still getting Workbox's precaching/runtime caching.
 *
 * Portfolio note: this pattern (custom SW + Workbox precache) is what
 * production PWAs use — the interviewee question is "how do you extend the
 * auto-generated service worker?" — answer: switch to injectManifest mode.
 */

import { precacheAndRoute } from 'workbox-precaching'

// __WB_MANIFEST is replaced at build time by VitePWA with the actual asset list
precacheAndRoute(self.__WB_MANIFEST)

// ── Push notification handler ─────────────────────────────────────────────────
//
// The browser calls this whenever the push service delivers a message from our
// backend (/push/send-weekly → pywebpush → push service → here).
// We MUST call showNotification() synchronously inside this handler; if we
// don't, the browser may suppress the notification with a generic warning.
self.addEventListener('push', event => {
  const body = event.data ? event.data.text() : 'Olha o auê dessa semana — vai junto?'
  event.waitUntil(
    self.registration.showNotification('auê 🎉', {
      body,
      icon: '/icon-192x192.png',
      badge: '/icon-192x192.png',
      tag: 'weekly-checkin',        // replaces previous notification of same tag
      renotify: true,               // vibrate/sound even if tag exists
      data: { url: '/' },
    })
  )
})

// ── Notification click handler ────────────────────────────────────────────────
// Focus or open the app when user taps the notification.
self.addEventListener('notificationclick', event => {
  event.notification.close()
  const targetUrl = event.notification.data?.url ?? '/'
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(windowClients => {
      for (const client of windowClients) {
        if (client.url.includes(targetUrl) && 'focus' in client) {
          return client.focus()
        }
      }
      return clients.openWindow(targetUrl)
    })
  )
})
