/**
 * auê custom service worker — injectManifest mode
 *
 * VitePWA's `injectManifest` mode takes this file, injects the precache
 * manifest generated by Workbox (list of hashed static assets), and outputs
 * the final SW into dist/.  We then add our own push event handler on top.
 *
 * Why injectManifest instead of generateSW?
 *   generateSW creates the SW entirely from config — no room to add custom
 *   event handlers like `push`.  injectManifest keeps full control while
 *   still getting Workbox's precaching/runtime caching.
 *
 * Portfolio note: this pattern (custom SW + Workbox precache) is what
 * production PWAs use — the interviewee question is "how do you extend the
 * auto-generated service worker?" — answer: switch to injectManifest mode.
 */

import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'

// __WB_MANIFEST is replaced at build time by VitePWA with the actual asset list
precacheAndRoute(self.__WB_MANIFEST)

// ── Auto-update on every deploy ──────────────────────────────────────────────
//
// VitePWA's `registerType: 'autoUpdate'` only works in `generateSW` mode; in
// `injectManifest` mode (which we use to attach the push handler) we have to
// drive the lifecycle ourselves.
//
// skipWaiting(): the new SW activates as soon as it finishes installing,
// without waiting for every tab/window to close — so a single reload after
// a deploy actually picks up the new chunks. Default Workbox behavior is
// to leave the old SW in charge until the user fully quits the PWA, which
// turns "Ctrl+Shift+R" into a question mark.
//
// clients.claim(): once activated, the SW takes over open pages immediately
// instead of waiting for the next navigation. Combined with skipWaiting,
// this means a reload right after deploy pulls the new shell + chunks.
//
// Tradeoff: a fetch in flight during the SW swap could read a mix of old
// and new chunks (tiny window). Self-corrects on the next navigation, and
// is much better than the alternative of users seeing stale code for days.
self.addEventListener('install', () => self.skipWaiting())
self.addEventListener('activate', (event) => event.waitUntil(self.clients.claim()))

// Navigation fallback: any in-scope navigation that's not a precached file
// gets the cached index.html so the SPA boots offline. We DENY a few server
// routes that must reach the backend (or we'd serve the React shell instead
// of e.g. the iOS install walkthrough or the privacy policy HTML).
const navigationHandler = createHandlerBoundToURL('/index.html')
registerRoute(new NavigationRoute(navigationHandler, {
  denylist: [
    /^\/install(\/|$|\?)/,     // /install universal walkthrough (server HTML)
    /^\/ios(\/|$|\?)/,         // /ios → /install redirect (back-compat)
    /^\/privacy(\/|$|\?)/,     // /privacy LGPD policy (server HTML)
    /^\/\.well-known\//,       // assetlinks.json + apple-app-site-association
    /^\/apple-app-site-association/,  // legacy AASA path (some iOS versions)
    /^\/manifest\.webmanifest/,// PWA manifest itself
    /^\/sw\.js/,               // service worker file
    /^\/registerSW\.js/,       // SW registration script
  ],
}))

// ── Push notification handler ─────────────────────────────────────────────────
//
// The browser calls this whenever the push service delivers a message from our
// backend (per-user pushes: group event added, friend RSVP'd, weekly broadcast).
// We MUST call showNotification() synchronously inside this handler; if we
// don't, the browser may suppress the notification with a generic warning.
//
// Payload format (per-user pushes): JSON {title, body, url, tag}
// Legacy format (weekly broadcast): plain text → used as body, generic title.
self.addEventListener('push', event => {
  let title = 'auê 🎉'
  let body = 'Olha o auê dessa semana — vai junto?'
  let url = '/'
  let tag = 'weekly-checkin'

  if (event.data) {
    try {
      const data = event.data.json()
      if (data.title) title = data.title
      if (data.body) body = data.body
      if (data.url) url = data.url
      if (data.tag) tag = data.tag
    } catch {
      // Plain-text payload (legacy weekly broadcast) — use it as body.
      body = event.data.text() || body
    }
  }

  event.waitUntil(
    self.registration.showNotification(title, {
      body,
      icon: '/icon-192x192.png',
      badge: '/icon-192x192.png',
      tag,                          // replaces previous notification of same tag
      renotify: true,               // vibrate/sound even if tag exists
      data: { url },
    })
  )
})

// ── Notification click handler ────────────────────────────────────────────────
// Focus or open the app when user taps the notification.
self.addEventListener('notificationclick', event => {
  event.notification.close()
  const targetUrl = event.notification.data?.url ?? '/'
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(windowClients => {
      for (const client of windowClients) {
        if (client.url.includes(targetUrl) && 'focus' in client) {
          return client.focus()
        }
      }
      return clients.openWindow(targetUrl)
    })
  )
})
